# Generated by Django 4.0.1 on 2022-01-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('news_body', models.CharField(max_length=3000)),
                ('is_public', models.BooleanField()),
                ('author', models.CharField(max_length=60)),
            ],
        ),
    ]
