# Generated by Django 4.0.1 on 2022-02-17 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_likes_alter_post_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_profile_link',
        ),
    ]
