# Generated by Django 4.0.1 on 2022-02-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_post_post_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isForFollowers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='isForGroups',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='isPublic',
            field=models.BooleanField(default=True),
        ),
    ]
